sudo: required

language: php

php:
  # Test against PHP 7.1.8 version ...
  - 7.1.8

services:
  - docker

before_script:
  - docker-compose -f docker-compose-dev.yml up --build -d
  - docker ps -a
  - sleep 50

after_script:
  - docker-compose -f docker-compose-dev.yml down
