version: '3.4'
services:
  php:
    image: jfernancordova/docker-laravel-api-dev:1.0.0
    environment:
      APP_NAME: docker-laravel-api-dev
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:B4svAvz1VlCE6iiaKUy/qlmiV2E5JTj7+kCfS5nJpZI=
      APP_LOG_LEVEL: debug
      APP_URL: "http://localhost"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: apiLaravelDocker
      DB_USERNAME: apiLaravelDocker
      DB_PASSWORD: apiLaravelDocker
      XDEBUG_MODE: 1
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - .:/docker-laravel-api-dev

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: apiLaravelDocker
      MYSQL_USER: apiLaravelDocker
      MYSQL_PASSWORD: apiLaravelDocker
      MYSQL_ROOT_PASSWORD: apiLaravelDocker
    volumes:
      - .docker/local-mysql-datadir:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
